# Generated by Django 4.0.4 on 2022-06-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('cuit', models.DecimalField(decimal_places=0, max_digits=11)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=13)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('iden_empres', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ma',
            },
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=3)),
                ('iten', models.CharField(max_length=100)),
                ('p_unitad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
