# Generated by Django 4.0.4 on 2022-06-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, verbose_name='Nombre Empresa')),
                ('cuit', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Cuit')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=13, verbose_name='Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Cantidad')),
                ('iten', models.CharField(max_length=100, verbose_name='Descripción Iten')),
                ('p_unitad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Unitario')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo Maquinaria')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, verbose_name='N° Serie')),
                ('iden_empres', models.CharField(blank=True, max_length=50, verbose_name='Iden interno de Empresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
            },
        ),
    ]
